{% set name = "scikit-allel" %}
{% set version = "1.3.0" %}
{% set sha256 = "cad547fe41bd7ee1fe04b6f3e44ef435ef11297db7fe56f1cc6eaf5929fd2c94" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - setuptools
    - setuptools_scm
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - scikit-learn
    - numexpr
    - dask >=0.15
    - h5py
    - bcolz
    - zarr >=2.2
    - numcodecs
    - matplotlib-base
    - seaborn
    - pandas
    - pomegranate

test:
  requires:
    - pytest
  imports:
    - allel
    - allel.opt.model
    - allel.opt.stats
    - allel.opt.io_vcf_read
  commands:
    # minimal tests for now, until we have a work sround for tests needing tabix
    - pytest -v --pyargs allel.test.test_api
about:
  home: http://github.com/cggh/scikit-allel
  license: MIT
  license_file: LICENSE
  summary: A Python package for exploring and analysing genetic variation data.
  doc_url: http://scikit-allel.readthedocs.io/
  dev_url: https://github.com/cggh/scikit-allel

extra:
  recipe-maintainers:
    - alimanfoo
    - hardingnj
    - leehart
