{% set name = "scikit-allel" %}
{% set version = "1.0.3" %}
{% set sha256 = "f1cb5318c757782e54e19b9d79ed7286b286edfd5cf019a4d53001d29f5d7bc6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy x.x
  run:
    - python
    - numpy x.x
    - scipy
    - scikit-learn
    - numexpr
    - dask >=0.11.1
    - h5py
    - bcolz
    - zarr
    - matplotlib
    - seaborn
    - pandas

test:
  requires:
    - nose
  imports:
    - allel
    - allel.opt.model
    - allel.opt.stats
  commands:
    - nosetests -v allel --exclude=gff3

about:
  home: http://github.com/cggh/scikit-allel
  license: MIT
  license_file: LICENSE
  summary: 'A Python package for exploring and analysing genetic variation data.'
  doc_url: http://scikit-allel.readthedocs.io/
  dev_url: https://github.com/cggh/scikit-allel

extra:
  recipe-maintainers:
    - alimanfoo
    - hardingnj
