{% set name = "scikit-allel" %}
{% set version = "1.3.7" %}
{% set sha256 = "cb6229c407451bf1ea4b7fa681188e142d24a3a168ca6e786b6b4a7e999507f4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # missing pomegranate PyTorch dependency >=1.9 for Windows 
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - setuptools
    - setuptools_scm
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - scikit-learn
    - numexpr
    - dask >=0.15
    - h5py
    - zarr >=2.2
    - numcodecs
    - matplotlib-base
    - seaborn
    - pandas
    - pomegranate >=1

test:
  requires:
    - pytest
  imports:
    - allel
    - allel.opt.model
    - allel.opt.stats
    - allel.opt.io_vcf_read
  commands:
    # minimal tests for now, until we have a work sround for tests needing tabix
    - pytest -v --pyargs allel.test.test_api
about:
  home: http://github.com/cggh/scikit-allel
  license: MIT
  license_file: LICENSE
  summary: A Python package for exploring and analysing genetic variation data.
  doc_url: http://scikit-allel.readthedocs.io/
  dev_url: https://github.com/cggh/scikit-allel

extra:
  recipe-maintainers:
    - tschuelia
    - alimanfoo
    - hardingnj
    - leehart
