# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "tbuf1YSuSkMcL7sWpuv2kcgI+JgSvd/mlBJZajABwEm+PZY3cCfwyx3cYdmXHyOfx5EHWVAi+QM40FXejhyePGRZek5N1shGD0fB8pFzjwbv6mDI0R2QbuT4f49SMvrKp8UZecxXdduxy03ciKvLkXw8vEN7PROgdvvrQ29qiLBLiPsU0Zj7Neqa7IBatiWlBk1u+XEx/bW2hmQYXapBs4gczkcP3eDRyfJxwynVa7vRA26xHjNHc3lyPX36ZtWOVFoC488VX1R4g77s1/Eq7e6P5vEPkuOIVxiI6NJ/yE3AtAIit5eh4WeFfoPqOzs7NyD3ClFbs4i0ZlNODVE65ph2SlCji2bxellJaP2dJlelRWylIwJBSiLEBiDuscPCFyUL0aHZIAnfl9Vfr2I3D3lJ7nR3aMVqRYjwa3vUjFrBKxXago92ulYav9/2pLs8kmScS3TzymMoGSWbaG3A2Fwt8F2t2dXgX8UxQO2q+s5j/xbLZDQ+716x45xmYLmbnDNM7oP9OLomt4HoxBrtQkMHXcqKS9guJr/jutwBCWrKAo6a3m+z1I10x9DxgsEZSHNgPgGtmM2UkSqJw6I+5IuxGPjLm1D5gIL12lq3HiXZ1of42p/Kpy5DosMfZX2hqDhattGVVCqWINj0cBuSWnWagklxPK6mcI9n/lQz3Xc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml