travis:
  secure:
    BINSTAR_TOKEN: tbuf1YSuSkMcL7sWpuv2kcgI+JgSvd/mlBJZajABwEm+PZY3cCfwyx3cYdmXHyOfx5EHWVAi+QM40FXejhyePGRZek5N1shGD0fB8pFzjwbv6mDI0R2QbuT4f49SMvrKp8UZecxXdduxy03ciKvLkXw8vEN7PROgdvvrQ29qiLBLiPsU0Zj7Neqa7IBatiWlBk1u+XEx/bW2hmQYXapBs4gczkcP3eDRyfJxwynVa7vRA26xHjNHc3lyPX36ZtWOVFoC488VX1R4g77s1/Eq7e6P5vEPkuOIVxiI6NJ/yE3AtAIit5eh4WeFfoPqOzs7NyD3ClFbs4i0ZlNODVE65ph2SlCji2bxellJaP2dJlelRWylIwJBSiLEBiDuscPCFyUL0aHZIAnfl9Vfr2I3D3lJ7nR3aMVqRYjwa3vUjFrBKxXago92ulYav9/2pLs8kmScS3TzymMoGSWbaG3A2Fwt8F2t2dXgX8UxQO2q+s5j/xbLZDQ+716x45xmYLmbnDNM7oP9OLomt4HoxBrtQkMHXcqKS9guJr/jutwBCWrKAo6a3m+z1I10x9DxgsEZSHNgPgGtmM2UkSqJw6I+5IuxGPjLm1D5gIL12lq3HiXZ1of42p/Kpy5DosMfZX2hqDhattGVVCqWINj0cBuSWnWagklxPK6mcI9n/lQz3Xc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
